# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revenium < Formula
  desc "Manage your Revenium account from the command line"
  homepage "https://github.com/revenium/revenium-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.1.0/revenium-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "ac674179c468616433d62bb0030476ec1d0f96729062d1c5248d090ff139a120"

      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.1.0/revenium-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "6350207aa4258bb0c69200e2f9472e5acb9bfdeae4717c1bdf4698aa4ff3fb8e"

      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.1.0/revenium-cli_1.1.0_linux_amd64.tar.gz"
      sha256 "d9f5d7e8110451415f9c53a529b30a9f789de79c6d66b86b6bb87f8140201fef"
      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.1.0/revenium-cli_1.1.0_linux_arm64.tar.gz"
      sha256 "064426697d59fe6877ca31baf9e55c533f54017ac01dd5a208fb2f1a19521e21"
      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
  end

  test do
    system "#{bin}/revenium", "version"
  end
end
