# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revenium < Formula
  desc "Manage your Revenium account from the command line"
  homepage "https://github.com/revenium/revenium-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.2.0/revenium-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "6624964edfc9a9531348fa8520d082de89050ebc7a362158c1547b6e6583e214"

      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.2.0/revenium-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "6922a5450afd0a82496fd17df9c4d1e1a0a79aaa72d3aa4e5866bd2eb3af0a17"

      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.2.0/revenium-cli_1.2.0_linux_amd64.tar.gz"
      sha256 "cc4b07e94589af082dc21ecba7e235ebc1dd52f010238fd932dec6003a816f67"
      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/revenium/revenium-cli/releases/download/v1.2.0/revenium-cli_1.2.0_linux_arm64.tar.gz"
      sha256 "f27d67a3cd5c268342710971650d58a15f730ce43f43b7b79c45a8133a26a0b7"
      define_method(:install) do
        bin.install "revenium"
        bash_completion.install "completions/revenium.bash" => "revenium"
        zsh_completion.install "completions/revenium.zsh" => "_revenium"
        fish_completion.install "completions/revenium.fish"
      end
    end
  end

  test do
    system "#{bin}/revenium", "version"
  end
end
